name: ci
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build cpplint image
        run: docker build cpplint/ -t cpplint
      - name: Check code in /src
        run: docker run -v ${PWD}:/app cpplint bash -c "find src/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py"
      - name: Check code in /tests
        run: docker run -v ${PWD}:/app cpplint bash -c "find tests/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py"
      - name: Check code in /exampes
        run: docker run -v ${PWD}:/app cpplint bash -c "find examples/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py"
  build:
    runs-on: ubuntu-latest
    needs: cpplint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{github.repository}}:latest
          outputs: type=docker,dest=/tmp/image.tar
          build-args: BUILD_TYPE=Debug
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar

  tests-without-auth:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp/
      - name: Run Reduct Storage
        run: docker run -p 8383:8383 -v ${PWD}/data:/data -d ghcr.io/reduct-storage/reduct-storage:latest

      - name: Load image with tests
        run: |
          docker load --input /tmp/image.tar
          docker image ls -a
      - name: Run tests
        run: docker run --network=host ${{github.repository}} reduct-tests

  tests-with-auth:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp/
      - name: Run Reduct Storage
        run: docker run -p 8383:8383 -v ${PWD}/data:/data -d --env RS_API_TOKEN=TOKEN ghcr.io/reduct-storage/reduct-storage:latest

      - name: Load image with tests
        run: |
          docker load --input /tmp/image.tar
          docker image ls -a
      - name: Run tests
        run: docker run --network=host --env REDUCT_CPP_TOKEN_API=TOKEN ${{github.repository}} reduct-tests
